version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/cors_support.conf:/etc/nginx/cors_support.conf:ro
      - ./nginx/configs/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
      - ./nginx/frontend:/usr/share/nginx/html
    #links:
    depends_on:
      - backend

  backend:
    image: asaramet/npm-run
    volumes:
      - ./node-express:/usr/src/app
      - ./nginx/ssl:/usr/src/app/ssl
    links:
      - mongo_db:mongo

  mongo_db:
    image: mongo:3.4
    volumes:
      - ./mongo_db/mongodb:/data/db
#      - data-db:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    links:
      - mongo_db:mongo

networks:
  default:
    external:
      name: haw_app

#volumes:
#  data-db:
