version: '3.1'

services:
  web:
    image: nginx:1.13
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    volumes:
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./nginx/ssl:/etc/ssl
      - ./html:/usr/share/nginx/html
    deploy:
      placement:
        constraints: [node.role == manager]

  mongo_db:
    image: mongo:3.4
    networks:
      - backend
    volumes:
      - data-db:/data/db

  node:
    image: node:8
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  data-db:
