var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var schema = new Schema({
  paresedfileID: {type: Schema.Types.ObjectId, ref:"Parsedfile"},
  moabExecutable: { type: String},
  moabSystemJID: { type : String},
  moabDstRM: { type : String},
  moabTemplateSets: { type : String},
  moabAName: { type : String},
  moabIWD: { type : String},
  moabUMask: { type : String},
  moabStartPriority: { type : String},
  moabSystemID: { type : String},
  moabPE: { type : String},
  moabAllocatedNodes: { type : String},
  moabStartCount: { type : String},
  moabBACKFILL: { type : String},
  moabTotalRequestedTasks: { type : String},
  moabSubmitDir: { type : String},
  moabGLOBALQUEUE: { type : String},
  moabTaskCount: { type : String},
  moabEffQueueTime: { type : String},
  moabUnicore: { type : String},
  moabNodeMatchPolicy: { type : String},
  moabPartition: { type : String},
  moabNodeAccess: { type : String},
  moabProcPerTask: { type : String},
  moabMemPerTask: { type : String},
  moabBypassCount: { type : String},
  moabDstRMJID: { type : String},
  moabAverageUtilizedProcs: { type : String},
  moabTimeQueuedTotal: { type : String},
  moabClass: { type : String},
  moabReqWallTime: { type : String},
  moabGroup: { type : String},
  moabUser: { type : String},
  moabJobId: { type : String},
  moabTotalRequestedNodes: { type : String},
  moabTotalRequestedProcs: { type : String},
  moabStartTime: { type : String},
  moabEndTime: { type : String},
  moabSubmitTime: { type : String},
  moabUsedWallTime: { type : String},
  moabTotalRequestedMemory: { type : String},
  moabTotalCost: { type : String},
  moabAccount: { type : String}
});

module.exports = mongoose.model('Moabjob', schema);
