var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var schema = new Schema({
  //Executable: { type: String},
  //SystemJID: { type : String},
  //DstRM: { type : String},
  //TemplateSets: { type : String},
  //AName: { type : String},
  //IWD: { type : String},
  //UMask: { type : String},
  //StartPriority: { type : String},
  //SystemID: { type : String},
  //PE: { type : String},
  //AllocatedNodes: { type : String},
  //StartCount: { type : String},
  //BACKFILL: { type : String},
  //TotalRequestedTasks: { type : String},
  //SubmitDir: { type : String},
  //GLOBALQUEUE: { type : String},
  //TaskCount: { type : String},
  //EffQueueTime: { type : String},
  //Unicore: { type : String},
  //NodeMatchPolicy: { type : String},
  //Partition: { type : String},
  //NodeAccess: { type : String},
  //ProcPerTask: { type : String},
  //MemPerTask: { type : String},
  //BypassCount: { type : String},
  //DstRMJID: { type : String},
  //AverageUtilizedProcs: { type : String},
  //TimeQueuedTotal: { type : String},
  //Class: { type : String},
  //ReqWallTime: { type : String},
  Group: { type : String},
  User: { type : String},
  JobId: { type : String},
  TotalRequestedNodes: { type : String},
  TotalRequestedProcs: { type : String},
  StartTime: { type : String},
  EndTime: { type : String},
  SubmitTime: { type : String},
  UsedWallTime: { type : String},
  TotalRequestedMemory: { type : String},
  TotalCost: { type : String},
  Account: { type : String}
},{collection: 'haw'});

module.exports = mongoose.model('Statistics', schema);
